FROM node:7.2.0

MAINTAINER MJ Berends <mjr.berends@gmail.com>

LABEL org.approximatelylinear.project=trans_passports
LABEL com.approximatelylinear.projectRole=frontend

RUN apt-get update && apt-get install -y --no-install-recommends \
	&& rm -rf /var/lib/apt/lists/*

ENV NODE_ENV $NODE_ENV

# Create user for this app
RUN groupadd -r trans_passports && \
	useradd -r -g trans_passports trans_passports

RUN mkdir -p /opt/trans_passports
RUN mkdir -p /opt/src
WORKDIR /opt/trans_passports

# Install node deps
COPY /code/trans-passports-react/package.json /opt/trans_passports/package.json
COPY /code/trans-passports-react/webpack.config.js /opt/trans_passports/webpack.config.js
RUN npm install
#	Move it over to a tmp location so that we can move it back upon volume linking
RUN cp -r /opt/trans_passports/* /opt/src

RUN mkdir /opt/bin
COPY bin/run_frontend.sh /opt/bin
RUN chown :trans_passports /opt/bin/* \
	&& chmod g+r,g+x /opt/bin/*

# Copy over the rest of the codebase
COPY /code/trans-passports-react /opt/trans_passports

RUN chown -R :trans_passports /opt/trans_passports \
	&& chmod -R g+r,g+w,g+x /opt/trans_passports

CMD [ "/opt/bin/run_frontend.sh" ]

USER trans_passports
