version: '2'
services:
  # trans_passports_main:
  #   container_name: trans_passports_main
  #   volumes:
  #     - ../:/opt/trans_passports:Z # Label the volume as private and unshared
  #   volumes_from:
  #     - logs
  #   build:
  #     context: ../
  #     dockerfile: docker/Dockerfile_app
  #   command: /opt/startup_trans_passports_app_local.sh
  #   ports:
  #     - "5000:5000"
  #   environment:
  #     TZ: UTC
  #     ENV: local
  #     ENVIRONMENT_SETTING: development
  #   ulimits:
  #     nproc: 65535
  #     nofile:
  #       soft: 20000
  #       hard: 40000
  trans_passports_frontend:
    volumes:
      - ../code/trans-passports-react:/opt/trans_passports:Z # Label the volume as private and unshared
    build:
      context: ../
      dockerfile: docker/Dockerfile_frontend
    command: /opt/bin/run_frontend.sh
    ports:
      - "8080:8080"
    env_file:
      - ../frontend.env
    depends_on:
      # - trans_passports_db_data
      - trans_passports_db
      # - trans_passports_redis_data
      - trans_passports_redis
      - trans_passports_api

  trans_passports_api:
    volumes:
      - ../code/trans-passports-api:/opt/trans_passports:Z # Label the volume as private and unshared
    build:
      context: ../
      dockerfile: docker/Dockerfile_api
    command: /opt/bin/run_api.sh
    ports:
      - "3000:3000"
    env_file:
      - ../api.env
    depends_on:
      # - trans_passports_db_data
      - trans_passports_db
      # - trans_passports_redis_data
      - trans_passports_redis

  trans_passports_redis:
    container_name: trans_passports_redis
    image: redis
    env_file:
      - ../redis.env
    # volumes_from:
    #   - trans_passports_redis_data

  # trans_passports_redis_data:
  #   container_name: trans_passports_redis_data
  #   image: redis
  #   volumes:
  #     - '/data'
  #   command: '/bin/true'

  trans_passports_db:
    container_name: trans_passports_db
    image: postgres
    env_file:
      - ../postgres.env
    # volumes_from:
    #   - trans_passports_db_data

  # trans_passports_db_data:
  #   container_name: trans_passports_db_data
  #   image: postgres
  #   volumes:
  #     - '/data'
  #   command: '/bin/true'

  # nginx:
  #   container_name: nginx
  #   build:
  #     context: ../
  #     dockerfile: docker/Dockerfile_nginx
  #   ports:
  #     - "80:80"
  #   volumes_from:
  #     - logs
  #     - trans_passports_main
  #   links:
  #     - trans_passports_main:app
